# Generated by Django 3.2.4 on 2021-06-25 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='routine',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='registration',
            name='date',
            field=models.DateTimeField(default='2078-03-11'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date',
            field=models.DateField(default='2078-03-11'),
        ),
        migrations.AlterField(
            model_name='staff_leave_application',
            name='endate',
            field=models.DateField(default='2078-03-11'),
        ),
        migrations.AlterField(
            model_name='staff_leave_application',
            name='received_date',
            field=models.DateTimeField(default='2078-03-11'),
        ),
        migrations.AlterField(
            model_name='staff_leave_application',
            name='startdate',
            field=models.DateField(default='2078-03-11'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.period'),
        ),
    ]
