# Generated by Django 3.2.4 on 2021-06-25 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20210625_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='routine',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.periods'),
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
