# Generated by Django 3.2.4 on 2021-06-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=300)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('district', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
